// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package otel

import (
	"strings"
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	dbpreview "github.com/documentdb/documentdb-operator/api/preview"
)

func TestOtel(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Otel Suite")
}

var _ = Describe("ConfigMapName", func() {
	It("returns the expected ConfigMap name", func() {
		Expect(ConfigMapName("my-cluster")).To(Equal("my-cluster-otel-config"))
	})
})

var _ = Describe("GenerateBaseYAML", func() {
	It("generates YAML with debug exporter only when no OTLP exporter is configured", func() {
		spec := &dbpreview.MonitoringSpec{
			Enabled: true,
		}
		result := GenerateBaseYAML("test-cluster", "test-ns", spec)

		Expect(result).To(ContainSubstring("# Auto-generated by documentdb-operator"))
		Expect(result).To(ContainSubstring("documentdb.cluster"))
		Expect(result).To(ContainSubstring(`"test-cluster"`))
		Expect(result).To(ContainSubstring("k8s.namespace.name"))
		Expect(result).To(ContainSubstring(`"test-ns"`))
		Expect(result).To(ContainSubstring("k8s.pod.name"))
		Expect(result).To(ContainSubstring("${POD_NAME}"))
		Expect(result).To(ContainSubstring("debug:"))
		Expect(result).To(ContainSubstring("verbosity: basic"))
		// OTLP exporter should not appear — only the OTLP receiver is present
		Expect(result).NotTo(ContainSubstring("insecure:"))
		// Pipeline section
		Expect(result).To(ContainSubstring("service:"))
		Expect(result).To(ContainSubstring("pipelines:"))
		Expect(result).To(ContainSubstring("metrics:"))
		Expect(result).To(ContainSubstring("- debug"))
		// Receivers
		Expect(result).To(ContainSubstring("- hostmetrics"))
		Expect(result).To(ContainSubstring("- sqlquery/connections"))
		Expect(result).To(ContainSubstring("- sqlquery/replication"))
		Expect(result).To(ContainSubstring("- sqlquery/index_stats"))
		// Processors
		Expect(result).To(ContainSubstring("batch:"))
		Expect(result).To(ContainSubstring("send_batch_size: 1024"))
		Expect(result).To(ContainSubstring("timeout: 5s"))
		Expect(result).To(ContainSubstring("resource:"))
		// OTLP receiver
		Expect(result).To(ContainSubstring("0.0.0.0:4317"))
	})

	It("includes OTLP exporter when configured", func() {
		spec := &dbpreview.MonitoringSpec{
			Enabled: true,
			Exporter: &dbpreview.ExporterSpec{
				OTLP: &dbpreview.OTLPExporterSpec{
					Endpoint: "otel-collector.monitoring:4317",
					Insecure: true,
				},
			},
		}
		result := GenerateBaseYAML("prod-cluster", "prod-ns", spec)

		Expect(result).To(ContainSubstring(`"prod-cluster"`))
		Expect(result).To(ContainSubstring(`"prod-ns"`))
		// OTLP exporter section
		Expect(result).To(ContainSubstring("otlp:"))
		Expect(result).To(ContainSubstring(`"otel-collector.monitoring:4317"`))
		Expect(result).To(ContainSubstring("insecure: true"))
		// Pipeline should include both exporters
		Expect(result).To(ContainSubstring("- debug"))
		Expect(result).To(ContainSubstring("- otlp"))
	})

	It("sets insecure to false when configured", func() {
		spec := &dbpreview.MonitoringSpec{
			Enabled: true,
			Exporter: &dbpreview.ExporterSpec{
				OTLP: &dbpreview.OTLPExporterSpec{
					Endpoint: "secure-endpoint:4317",
					Insecure: false,
				},
			},
		}
		result := GenerateBaseYAML("cluster", "ns", spec)

		Expect(result).To(ContainSubstring("insecure: false"))
	})

	It("skips OTLP exporter when endpoint is empty", func() {
		spec := &dbpreview.MonitoringSpec{
			Enabled: true,
			Exporter: &dbpreview.ExporterSpec{
				OTLP: &dbpreview.OTLPExporterSpec{
					Endpoint: "",
				},
			},
		}
		result := GenerateBaseYAML("cluster", "ns", spec)

		// Should not include OTLP exporter
		lines := strings.Split(result, "\n")
		otlpExporterCount := 0
		for _, line := range lines {
			trimmed := strings.TrimSpace(line)
			if trimmed == "otlp:" {
				otlpExporterCount++
			}
		}
		// The receivers section has an "otlp:" for the OTLP receiver, but exporter section should not
		// Check that exporters section doesn't have the endpoint config
		Expect(result).NotTo(ContainSubstring(`endpoint: ""`))
		Expect(result).To(ContainSubstring("- debug"))
	})

	It("handles nil Exporter spec", func() {
		spec := &dbpreview.MonitoringSpec{
			Enabled:  true,
			Exporter: nil,
		}
		result := GenerateBaseYAML("cluster", "ns", spec)

		Expect(result).To(ContainSubstring("debug:"))
		Expect(result).To(ContainSubstring("- debug"))
	})
})
