// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package otel

import (
	_ "embed"
	"fmt"

	"gopkg.in/yaml.v3"

	dbpreview "github.com/documentdb/documentdb-operator/api/preview"
)

//go:embed base_config.yaml
var baseConfigYAML []byte

const defaultPrometheusPort = 8888

// collectorConfig represents the OTel Collector configuration structure.
type collectorConfig struct {
	Receivers  map[string]any `yaml:"receivers,omitempty"`
	Processors map[string]any `yaml:"processors,omitempty"`
	Exporters  map[string]any `yaml:"exporters,omitempty"`
	Service    serviceConfig  `yaml:"service"`
}

type serviceConfig struct {
	Pipelines map[string]pipelineConfig `yaml:"pipelines"`
}

type pipelineConfig struct {
	Receivers  []string `yaml:"receivers"`
	Processors []string `yaml:"processors,omitempty"`
	Exporters  []string `yaml:"exporters"`
}

// ConfigMapName returns the OTel ConfigMap name for a given DocumentDB cluster.
func ConfigMapName(clusterName string) string {
	return fmt.Sprintf("%s-otel-config", clusterName)
}

// GenerateConfigMapData returns the ConfigMap data entries for the OTel Collector.
// The config is split into two files that the collector merges at startup:
//   - static.yaml: receivers and batch processor from the embedded base_config.yaml.
//     Add new SQL metric queries to base_config.yaml — no Go code changes needed.
//   - dynamic.yaml: per-cluster resource attributes, exporters, and pipeline wiring.
//
// When monitoring is disabled, static.yaml contains an idle (nop) config and
// dynamic.yaml is empty, allowing monitoring to be toggled without pod restart.
func GenerateConfigMapData(clusterName, namespace string, spec *dbpreview.MonitoringSpec) (map[string]string, error) {
	if !spec.Enabled {
		return generateIdleConfigMapData(spec)
	}

	dynamicYAML, err := generateDynamicConfig(clusterName, namespace, spec)
	if err != nil {
		return nil, err
	}

	return map[string]string{
		"static.yaml":  string(baseConfigYAML),
		"dynamic.yaml": "# Auto-generated by documentdb-operator. Do not edit.\n" + dynamicYAML,
	}, nil
}

// generateDynamicConfig builds the per-cluster dynamic config: resource processor,
// exporters, and pipeline wiring. The OTel Collector deep-merges this with static.yaml.
func generateDynamicConfig(clusterName, namespace string, spec *dbpreview.MonitoringSpec) (string, error) {
	cfg := collectorConfig{
		Processors: map[string]any{
			"resource": map[string]any{
				"attributes": []map[string]any{
					{"key": "documentdb.cluster", "value": clusterName, "action": "upsert"},
					{"key": "k8s.namespace.name", "value": namespace, "action": "upsert"},
					{"key": "k8s.pod.name", "value": "${POD_NAME}", "action": "upsert"},
				},
			},
		},
	}

	exporterNames := []string{}

	if spec.Exporter != nil {
		if otlp := spec.Exporter.OTLP; otlp != nil && otlp.Endpoint != "" {
			if cfg.Exporters == nil {
				cfg.Exporters = map[string]any{}
			}
			cfg.Exporters["otlp"] = map[string]any{
				"endpoint": otlp.Endpoint,
				"tls": map[string]any{
					// TODO: Support TLS for OTLP exporter. Currently hardcoded to
					// insecure for in-cluster communication. When TLS is needed,
					// add TLS config fields to OTLPExporterSpec (certSecret, etc.).
					"insecure": true,
				},
			}
			exporterNames = append(exporterNames, "otlp")
		}

		if prom := spec.Exporter.Prometheus; prom != nil {
			if cfg.Exporters == nil {
				cfg.Exporters = map[string]any{}
			}
			port := prom.Port
			if port == 0 {
				port = defaultPrometheusPort
			}
			cfg.Exporters["prometheus"] = map[string]any{
				"endpoint": fmt.Sprintf("0.0.0.0:%d", port),
			}
			exporterNames = append(exporterNames, "prometheus")
		}
	}

	// Wire pipeline: receivers + batch from static.yaml, resource from this dynamic config
	if len(exporterNames) > 0 {
		cfg.Service = serviceConfig{
			Pipelines: map[string]pipelineConfig{
				"metrics": {
					Receivers:  []string{"sqlquery"},
					Processors: []string{"resource", "batch"},
					Exporters:  exporterNames,
				},
			},
		}
	}

	out, err := yaml.Marshal(&cfg)
	if err != nil {
		return "", fmt.Errorf("failed to marshal dynamic OTel config: %w", err)
	}

	return string(out), nil
}

// generateIdleConfigMapData returns ConfigMap data for when monitoring is disabled.
// Uses nop receiver/exporter to keep the collector running but idle.
// Prometheus exporter stays alive if configured, so readiness probes pass.
func generateIdleConfigMapData(spec *dbpreview.MonitoringSpec) (map[string]string, error) {
	cfg := collectorConfig{
		Receivers: map[string]any{
			// Use OTLP receiver on an unused port as a no-op data source.
			"otlp": map[string]any{
				"protocols": map[string]any{
					"grpc": map[string]any{
						"endpoint": "localhost:14317",
					},
				},
			},
		},
		Exporters: map[string]any{
			"debug": map[string]any{
				"verbosity": "basic",
			},
		},
	}

	exporterNames := []string{"debug"}

	// Keep Prometheus endpoint alive so readiness probes pass
	if spec.Exporter != nil && spec.Exporter.Prometheus != nil {
		port := spec.Exporter.Prometheus.Port
		if port == 0 {
			port = defaultPrometheusPort
		}
		cfg.Exporters["prometheus"] = map[string]any{
			"endpoint": fmt.Sprintf("0.0.0.0:%d", port),
		}
		exporterNames = append(exporterNames, "prometheus")
	}

	cfg.Service = serviceConfig{
		Pipelines: map[string]pipelineConfig{
			"metrics": {
				Receivers: []string{"otlp"},
				Exporters: exporterNames,
			},
		},
	}

	out, err := yaml.Marshal(&cfg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal idle config: %w", err)
	}

	idleYAML := "# Auto-generated by documentdb-operator. Monitoring disabled.\n" + string(out)

	return map[string]string{
		"static.yaml":  idleYAML,
		"dynamic.yaml": "# Monitoring disabled - no dynamic config.\n",
	}, nil
}

// ResolvePrometheusPort returns the effective Prometheus port from the spec,
// or 0 if Prometheus exporter is not configured.
func ResolvePrometheusPort(spec *dbpreview.MonitoringSpec) int32 {
	if spec == nil || spec.Exporter == nil || spec.Exporter.Prometheus == nil {
		return 0
	}
	if spec.Exporter.Prometheus.Port == 0 {
		return defaultPrometheusPort
	}
	return spec.Exporter.Prometheus.Port
}
