// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package otel

import (
	"fmt"

	"gopkg.in/yaml.v3"

	dbpreview "github.com/documentdb/documentdb-operator/api/preview"
)

const defaultPrometheusPort = 8888

// collectorConfig represents the OTel Collector configuration structure.
type collectorConfig struct {
	Receivers  map[string]any `yaml:"receivers"`
	Processors map[string]any `yaml:"processors"`
	Exporters  map[string]any `yaml:"exporters"`
	Service    serviceConfig  `yaml:"service"`
}

type serviceConfig struct {
	Pipelines map[string]pipelineConfig `yaml:"pipelines"`
}

type pipelineConfig struct {
	Receivers  []string `yaml:"receivers"`
	Processors []string `yaml:"processors"`
	Exporters  []string `yaml:"exporters"`
}

// ConfigMapName returns the OTel ConfigMap name for a given DocumentDB cluster.
func ConfigMapName(clusterName string) string {
	return fmt.Sprintf("%s-otel-config", clusterName)
}

// GenerateBaseYAML generates the OTel Collector base.yaml content from a MonitoringSpec.
// This is a minimal config with an OTLP receiver, resource processor, and exporters.
// Additional receivers (engine metrics, host metrics) will be added in follow-up PRs.
func GenerateBaseYAML(clusterName, namespace string, spec *dbpreview.MonitoringSpec) (string, error) {
	cfg := collectorConfig{
		Receivers: map[string]any{
			"otlp": map[string]any{
				"protocols": map[string]any{
					"grpc": map[string]any{
						"endpoint": "0.0.0.0:4317",
					},
				},
			},
		},
		Processors: map[string]any{
			"batch": map[string]any{
				"send_batch_size": 1024,
				"timeout":         "5s",
			},
			"resource": map[string]any{
				"attributes": []map[string]any{
					{"key": "documentdb.cluster", "value": clusterName, "action": "upsert"},
					{"key": "k8s.namespace.name", "value": namespace, "action": "upsert"},
					{"key": "k8s.pod.name", "value": "${POD_NAME}", "action": "upsert"},
				},
			},
		},
		Exporters: map[string]any{
			"debug": map[string]any{
				"verbosity": "basic",
			},
		},
	}

	exporterNames := []string{"debug"}

	if spec.Exporter != nil {
		if otlp := spec.Exporter.OTLP; otlp != nil && otlp.Endpoint != "" {
			cfg.Exporters["otlp"] = map[string]any{
				"endpoint": otlp.Endpoint,
				"tls": map[string]any{
					"insecure": true,
				},
			}
			exporterNames = append(exporterNames, "otlp")
		}

		if prom := spec.Exporter.Prometheus; prom != nil {
			port := prom.Port
			if port == 0 {
				port = defaultPrometheusPort
			}
			cfg.Exporters["prometheus"] = map[string]any{
				"endpoint": fmt.Sprintf("0.0.0.0:%d", port),
			}
			exporterNames = append(exporterNames, "prometheus")
		}
	}

	cfg.Service = serviceConfig{
		Pipelines: map[string]pipelineConfig{
			"metrics": {
				Receivers:  []string{"otlp"},
				Processors: []string{"resource", "batch"},
				Exporters:  exporterNames,
			},
		},
	}

	out, err := yaml.Marshal(&cfg)
	if err != nil {
		return "", fmt.Errorf("failed to marshal OTel Collector config: %w", err)
	}

	return "# Auto-generated by documentdb-operator. Do not edit.\n" + string(out), nil
}

// ResolvePrometheusPort returns the effective Prometheus port from the spec,
// or 0 if Prometheus exporter is not configured.
func ResolvePrometheusPort(spec *dbpreview.MonitoringSpec) int32 {
	if spec == nil || spec.Exporter == nil || spec.Exporter.Prometheus == nil {
		return 0
	}
	if spec.Exporter.Prometheus.Port == 0 {
		return defaultPrometheusPort
	}
	return spec.Exporter.Prometheus.Port
}
