apiVersion: documentdb.io/preview
kind: DocumentDB
metadata:
  name: demo-documentdb
  namespace: app-namespace
spec:
  nodeCount: 1
  instancesPerNode: 1
  documentDBImage: ghcr.io/microsoft/documentdb/documentdb-local:16
  gatewayImage: ghcr.io/microsoft/documentdb/documentdb-local:16
  documentDbCredentialSecret: documentdb-credentials
  resource:
    storage:
      pvcSize: 5Gi
  exposeViaService:
    serviceType: ClusterIP
  logLevel: info
  sidecarInjectorPluginName: cnpg-i-sidecar-injector.documentdb.io
