{{- if .Values.cnpg.install }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "documentdb-chart.cnpgNamespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "documentdb-chart.name" . }}
    app.kubernetes.io/managed-by: "Helm"
{{- end }}