apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "documentdb-operator.serviceAccountName" . }}
  namespace: {{ include "documentdb-operator.namespace" . }}
  labels:
    {{- include "documentdb-operator.labels" (dict "root" $ "component" "operator") | nindent 4 }}
