apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: documentdb-operator-cluster-rolebinding
  labels:
    {{- include "documentdb-operator.labels" (dict "root" $ "component" "operator") | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "documentdb-operator.serviceAccountName" . }}
  namespace: {{ include "documentdb-operator.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: documentdb-operator-cluster-role
