# Namespace definition
apiVersion: v1
kind: Namespace
metadata:
  name: documentdb-preview-ns

---

apiVersion: v1
kind: Secret
metadata:
  name: documentdb-credentials
  namespace: documentdb-preview-ns
type: Opaque
stringData:
  username: default_user
  password: {{DOCUMENTDB_PASSWORD}}

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-cross-region-issuer
  namespace: documentdb-preview-ns
spec:
  selfSigned: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: cross-region-client-cert
  namespace: documentdb-preview-ns
  labels:
    cnpg.io/reload: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cross-region-client-cert
  namespace: documentdb-preview-ns
spec:
  secretName: cross-region-client-cert
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: selfsigned-cross-region-issuer
    kind: Issuer
    group: cert-manager.io

---

apiVersion: documentdb.io/preview
kind: DocumentDB
metadata:
  name: documentdb-preview
  namespace: documentdb-preview-ns
spec:
  nodeCount: 1
  instancesPerNode: 1
  resource:
    storage:
      pvcSize: 10Gi
  environment: aks
  clusterReplication:
    highAvailability: true
    replicationTLSSecret: cross-region-client-cert
    clientCASecret: cross-region-client-cert
    crossCloudNetworkingStrategy: AzureFleet
    primary: {{PRIMARY_CLUSTER}}
    clusterList:
{{CLUSTER_LIST}}
  exposeViaService:
    serviceType: LoadBalancer
  logLevel: info

---

apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: documentdb-namespace-crp
spec:
  resourceSelectors:
    - group: ""
      version: v1
      kind: Namespace
      name: documentdb-preview-ns
      selectionScope: NamespaceOnly # only namespace itself is placed, no resources within the namespace
  policy:
    placementType: PickAll
  strategy:
    type: RollingUpdate

---
# Application team manages resources using RP
apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ResourcePlacement
metadata:
  name: documentdb-resource-rp
  namespace: documentdb-preview-ns
spec:
  resourceSelectors:
    - group: documentdb.io
      kind: DocumentDB
      version: preview
      name: documentdb-preview
    - group: ""
      version: v1
      kind: Secret
      name: documentdb-credentials
    - group: ""
      version: v1
      kind: Secret
      name: cross-region-client-cert
  policy:
    placementType: PickAll
    affinity:
      clusterAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          clusterSelectorTerms:
            - labelSelector:
                matchExpressions:
                  - key: documentdb.io/fleet-hub
                    operator: DoesNotExist
            - labelSelector:
                matchExpressions:
                  - key: documentdb.io/fleet-hub
                    operator: NotIn
                    values:
                      - "true"
  strategy:
    type: RollingUpdate
